"""aggiunge backoff anti brute-force su utenti

Revision ID: 09a36b6fc538
Revises: 2480529b19e6
Create Date: 2026-06-19 14:31:58.470620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09a36b6fc538'
down_revision: Union[str, Sequence[str], None] = '2480529b19e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utenti', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tentativi_falliti_login', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('bloccato_fino', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utenti', schema=None) as batch_op:
        batch_op.drop_column('bloccato_fino')
        batch_op.drop_column('tentativi_falliti_login')

    # ### end Alembic commands ###
