"""baseline schema unificato

Squash di tutta la cronologia precedente (8e0594ee3d95 ... n8o9p0q1r2s3):
la prima migrazione della vecchia catena presupponeva che le tabelle base
esistessero già (create_all() pre-Alembic), quindi "alembic upgrade head"
non riusciva a costruire lo schema da zero (nuovo ambiente, DB locale
ripristinato). Questa migrazione crea l'intero schema in un colpo solo,
generata via autogenerate confrontando un DB vuoto con i modelli attuali.

In produzione lo schema esiste già: non va eseguita "upgrade", va fatto
"alembic stamp 2480529b19e6" per allineare alembic_version senza toccare
i dati. Vedi istruzioni di deploy.

Revision ID: 2480529b19e6
Revises:
Create Date: 2026-06-19 08:45:43.443673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models


# revision identifiers, used by Alembic.
revision: str = '2480529b19e6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('utente_id', sa.Integer(), nullable=False),
    sa.Column('attore_id', sa.Integer(), nullable=False),
    sa.Column('attore_username', sa.String(), nullable=False),
    sa.Column('azione', sa.String(), nullable=False),
    sa.Column('tabella', sa.String(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('dettaglio', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('ix_audit_log_utente_ts', ['utente_id', 'timestamp'], unique=False)

    op.create_table('utenti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('data_registrazione', app.models.FlexDate(), nullable=True),
    sa.Column('attivo', sa.Integer(), nullable=False),
    sa.Column('piano', sa.String(), nullable=True),
    sa.Column('pro_scadenza', app.models.FlexDate(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(), nullable=True),
    sa.Column('onboarding_done', sa.Boolean(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('email_verificato', sa.Boolean(), nullable=False),
    sa.Column('token_verifica', sa.String(), nullable=True),
    sa.Column('token_reset', sa.String(), nullable=True),
    sa.Column('token_reset_scadenza', sa.String(), nullable=True),
    sa.Column('accetta_termini', sa.Boolean(), nullable=True),
    sa.Column('titolare_id', sa.Integer(), nullable=True),
    sa.Column('ruolo', sa.String(), nullable=True),
    sa.Column('totp_secret', app.models.EncryptedString(), nullable=True),
    sa.Column('totp_abilitato', sa.Boolean(), nullable=False),
    sa.Column('data_aggiornamento', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['titolare_id'], ['utenti.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('utenti', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_utenti_id'), ['id'], unique=False)

    op.create_table('clienti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utente_id', sa.Integer(), nullable=True),
    sa.Column('tipo_cliente', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('cognome', sa.String(), nullable=True),
    sa.Column('ragione_sociale', sa.String(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('indirizzo', sa.String(), nullable=True),
    sa.Column('citta', sa.String(), nullable=True),
    sa.Column('provincia', sa.String(), nullable=True),
    sa.Column('cap', sa.String(), nullable=True),
    sa.Column('partita_iva', sa.String(), nullable=True),
    sa.Column('codice_fiscale', sa.String(), nullable=True),
    sa.Column('codice_destinatario', sa.String(), nullable=True),
    sa.Column('pec_destinatario', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('token_portale', sa.String(), nullable=True),
    sa.Column('token_portale_scadenza', sa.Date(), nullable=True),
    sa.Column('data_creazione', app.models.FlexDateTime(), nullable=False),
    sa.Column('data_aggiornamento', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['utente_id'], ['utenti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clienti', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clienti_id'), ['id'], unique=False)
        batch_op.create_index('ix_clienti_utente_id', ['utente_id'], unique=False)

    op.create_table('fornitori',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utente_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('partita_iva', sa.String(), nullable=True),
    sa.Column('codice_fiscale', sa.String(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('indirizzo', sa.String(), nullable=True),
    sa.Column('citta', sa.String(), nullable=True),
    sa.Column('provincia', sa.String(), nullable=True),
    sa.Column('cap', sa.String(), nullable=True),
    sa.Column('sito_web', sa.String(), nullable=True),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('data_creazione', app.models.FlexDateTime(), nullable=False),
    sa.Column('data_aggiornamento', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['utente_id'], ['utenti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fornitori', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fornitori_id'), ['id'], unique=False)

    op.create_table('impostazioni_azienda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utente_id', sa.Integer(), nullable=False),
    sa.Column('nome_azienda', sa.String(), nullable=True),
    sa.Column('partita_iva', sa.String(), nullable=True),
    sa.Column('codice_fiscale', sa.String(), nullable=True),
    sa.Column('regime_fiscale', sa.String(), nullable=True),
    sa.Column('indirizzo', sa.String(), nullable=True),
    sa.Column('cap', sa.String(), nullable=True),
    sa.Column('citta', sa.String(), nullable=True),
    sa.Column('provincia', sa.String(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('ultimo_numero_pdf', sa.Integer(), nullable=False),
    sa.Column('ultimo_numero_preventivo', sa.Integer(), nullable=False),
    sa.Column('ultimo_numero_fattura', sa.Integer(), nullable=False),
    sa.Column('ultimo_anno_fattura', sa.Integer(), nullable=True),
    sa.Column('obiettivo_mensile', sa.Float(), nullable=True),
    sa.Column('logo_path', sa.String(), nullable=True),
    sa.Column('aliquota_iva_default', sa.Float(), nullable=True),
    sa.Column('pec_indirizzo', sa.String(), nullable=True),
    sa.Column('pec_smtp_host', sa.String(), nullable=True),
    sa.Column('pec_smtp_port', sa.Integer(), nullable=True),
    sa.Column('pec_smtp_password', app.models.EncryptedString(), nullable=True),
    sa.Column('invio_automatico_sdi', sa.Boolean(), nullable=False),
    sa.Column('data_aggiornamento', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['utente_id'], ['utenti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('impostazioni_azienda', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_impostazioni_azienda_id'), ['id'], unique=False)

    op.create_table('inviti_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titolare_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('scadenza', app.models.FlexDate(), nullable=False),
    sa.Column('usato', sa.Integer(), nullable=True),
    sa.Column('data_creazione', app.models.FlexDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['titolare_id'], ['utenti.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('inviti_account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inviti_account_id'), ['id'], unique=False)

    op.create_table('listino_voci',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utente_id', sa.Integer(), nullable=False),
    sa.Column('descrizione', sa.String(), nullable=False),
    sa.Column('unita_misura', sa.String(), nullable=True),
    sa.Column('prezzo_unitario', sa.Float(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('data_creazione', app.models.FlexDateTime(), nullable=False),
    sa.Column('data_aggiornamento', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['utente_id'], ['utenti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('listino_voci', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listino_voci_id'), ['id'], unique=False)

    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utente_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('subscription_json', sa.Text(), nullable=False),
    sa.Column('creata_il', app.models.FlexDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['utente_id'], ['utenti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_push_subscriptions_id'), ['id'], unique=False)

    op.create_table('template_preventivi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utente_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('titolo', sa.String(), nullable=True),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('importo_preventivato', sa.Float(), nullable=True),
    sa.Column('aliquota_iva', sa.Float(), nullable=True),
    sa.Column('sconto', sa.Float(), nullable=True),
    sa.Column('note_consuntivo', sa.Text(), nullable=True),
    sa.Column('creato_il', app.models.FlexDateTime(), nullable=True),
    sa.Column('data_aggiornamento', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['utente_id'], ['utenti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('template_preventivi', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_template_preventivi_id'), ['id'], unique=False)

    op.create_table('lavori',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('utente_id', sa.Integer(), nullable=True),
    sa.Column('data_lavoro', app.models.FlexDate(), nullable=False),
    sa.Column('titolo', sa.String(), nullable=False),
    sa.Column('numero_preventivo', sa.String(), nullable=True),
    sa.Column('data_invio_preventivo', app.models.FlexDate(), nullable=True),
    sa.Column('data_accettazione_preventivo', app.models.FlexDate(), nullable=True),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('stato', sa.String(), nullable=False),
    sa.Column('priorita', sa.String(), nullable=False),
    sa.Column('importo_preventivato', sa.Float(), nullable=True),
    sa.Column('importo_consuntivo', sa.Float(), nullable=True),
    sa.Column('ore_lavoro', sa.Float(), nullable=True),
    sa.Column('costo_orario', sa.Float(), nullable=True),
    sa.Column('totale_materiali', sa.Float(), nullable=True),
    sa.Column('totale_manodopera', sa.Float(), nullable=True),
    sa.Column('margine', sa.Float(), nullable=True),
    sa.Column('aliquota_iva', sa.Float(), nullable=True),
    sa.Column('sconto', sa.Float(), nullable=True),
    sa.Column('totale_iva', sa.Float(), nullable=True),
    sa.Column('totale_documento', sa.Float(), nullable=True),
    sa.Column('stato_pagamento', sa.String(), nullable=True),
    sa.Column('importo_pagato', sa.Float(), nullable=True),
    sa.Column('residuo_pagamento', sa.Float(), nullable=True),
    sa.Column('data_scadenza_pagamento', app.models.FlexDate(), nullable=True),
    sa.Column('numero_fattura', sa.Integer(), nullable=True),
    sa.Column('data_fattura', app.models.FlexDate(), nullable=True),
    sa.Column('stato_fattura', sa.String(), nullable=True),
    sa.Column('note_consuntivo', sa.Text(), nullable=True),
    sa.Column('ritenuta_acconto', sa.Boolean(), nullable=False),
    sa.Column('aliquota_ritenuta', sa.Float(), nullable=True),
    sa.Column('token_firma', sa.String(), nullable=True),
    sa.Column('firma_nome_cliente', sa.String(), nullable=True),
    sa.Column('firma_ip', sa.String(), nullable=True),
    sa.Column('data_fine_prevista', app.models.FlexDate(), nullable=True),
    sa.Column('assegnato_a_id', sa.Integer(), nullable=True),
    sa.Column('data_creazione', app.models.FlexDateTime(), nullable=False),
    sa.Column('data_aggiornamento', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['assegnato_a_id'], ['utenti.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clienti.id'], ),
    sa.ForeignKeyConstraint(['utente_id'], ['utenti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lavori', schema=None) as batch_op:
        batch_op.create_index('ix_lavori_cliente_id', ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lavori_id'), ['id'], unique=False)
        batch_op.create_index('ix_lavori_utente_id', ['utente_id'], unique=False)
        batch_op.create_index('ix_lavori_utente_stato', ['utente_id', 'stato'], unique=False)
        batch_op.create_index('ix_lavori_utente_stato_fattura', ['utente_id', 'stato_fattura'], unique=False)

    op.create_table('materiali',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utente_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('unita_misura', sa.String(), nullable=True),
    sa.Column('quantita', sa.Float(), nullable=False),
    sa.Column('scorta_minima', sa.Float(), nullable=True),
    sa.Column('prezzo_acquisto_pieno', sa.Float(), nullable=True),
    sa.Column('prezzo_acquisto_scontato', sa.Float(), nullable=True),
    sa.Column('prezzo_vendita_default', sa.Float(), nullable=True),
    sa.Column('fornitore_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('data_creazione', app.models.FlexDateTime(), nullable=False),
    sa.Column('data_aggiornamento', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['fornitore_id'], ['fornitori.id'], ),
    sa.ForeignKeyConstraint(['utente_id'], ['utenti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('materiali', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_materiali_id'), ['id'], unique=False)
        batch_op.create_index('ix_materiali_utente_id', ['utente_id'], unique=False)

    op.create_table('promemoria_clienti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utente_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('titolo', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('data_promemoria', app.models.FlexDate(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('stato', sa.String(), nullable=False),
    sa.Column('data_creazione', app.models.FlexDateTime(), nullable=False),
    sa.Column('data_aggiornamento', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clienti.id'], ),
    sa.ForeignKeyConstraint(['utente_id'], ['utenti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('promemoria_clienti', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_promemoria_clienti_id'), ['id'], unique=False)
        batch_op.create_index('ix_promemoria_utente_id', ['utente_id'], unique=False)

    op.create_table('allegati_lavoro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utente_id', sa.Integer(), nullable=False),
    sa.Column('lavoro_id', sa.Integer(), nullable=False),
    sa.Column('nome_file', sa.String(), nullable=False),
    sa.Column('percorso_file', sa.String(), nullable=False),
    sa.Column('tipo_file', sa.String(), nullable=True),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('data_creazione', app.models.FlexDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lavoro_id'], ['lavori.id'], ),
    sa.ForeignKeyConstraint(['utente_id'], ['utenti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('allegati_lavoro', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_allegati_lavoro_id'), ['id'], unique=False)

    op.create_table('carichi_materiale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utente_id', sa.Integer(), nullable=False),
    sa.Column('materiale_id', sa.Integer(), nullable=False),
    sa.Column('quantita_iniziale', sa.Float(), nullable=False),
    sa.Column('quantita_residua', sa.Float(), nullable=False),
    sa.Column('prezzo_acquisto', sa.Float(), nullable=False),
    sa.Column('prezzo_vendita_default', sa.Float(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('data_carico', app.models.FlexDate(), nullable=False),
    sa.ForeignKeyConstraint(['materiale_id'], ['materiali.id'], ),
    sa.ForeignKeyConstraint(['utente_id'], ['utenti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('carichi_materiale', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_carichi_materiale_id'), ['id'], unique=False)

    op.create_table('documenti_pdf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utente_id', sa.Integer(), nullable=False),
    sa.Column('lavoro_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('nome_file', sa.String(), nullable=False),
    sa.Column('percorso_file', sa.String(), nullable=False),
    sa.Column('data_creazione', app.models.FlexDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lavoro_id'], ['lavori.id'], ),
    sa.ForeignKeyConstraint(['utente_id'], ['utenti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documenti_pdf', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documenti_pdf_id'), ['id'], unique=False)

    op.create_table('fatture_acquisto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utente_id', sa.Integer(), nullable=False),
    sa.Column('fornitore_id', sa.Integer(), nullable=True),
    sa.Column('lavoro_id', sa.Integer(), nullable=True),
    sa.Column('numero_fattura', sa.String(), nullable=True),
    sa.Column('data_fattura', app.models.FlexDate(), nullable=False),
    sa.Column('anno', sa.Integer(), nullable=False),
    sa.Column('data_scadenza', app.models.FlexDate(), nullable=True),
    sa.Column('descrizione', sa.String(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('importo_imponibile', sa.Float(), nullable=True),
    sa.Column('aliquota_iva', sa.Float(), nullable=True),
    sa.Column('importo_iva', sa.Float(), nullable=True),
    sa.Column('importo_totale', sa.Float(), nullable=True),
    sa.Column('stato_pagamento', sa.String(), nullable=False),
    sa.Column('data_pagamento', app.models.FlexDate(), nullable=True),
    sa.Column('metodo_pagamento', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('data_creazione', app.models.FlexDateTime(), nullable=False),
    sa.Column('data_aggiornamento', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['fornitore_id'], ['fornitori.id'], ),
    sa.ForeignKeyConstraint(['lavoro_id'], ['lavori.id'], ),
    sa.ForeignKeyConstraint(['utente_id'], ['utenti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fatture_acquisto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fatture_acquisto_id'), ['id'], unique=False)
        batch_op.create_index('ix_fatture_acquisto_utente_anno', ['utente_id', 'anno'], unique=False)
        batch_op.create_index('ix_fatture_acquisto_utente_id', ['utente_id'], unique=False)

    op.create_table('fatture_emesse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utente_id', sa.Integer(), nullable=False),
    sa.Column('lavoro_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('anno', sa.Integer(), nullable=False),
    sa.Column('data_emissione', app.models.FlexDate(), nullable=False),
    sa.Column('importo_imponibile', sa.Float(), nullable=True),
    sa.Column('importo_iva', sa.Float(), nullable=True),
    sa.Column('importo_bollo', sa.Float(), nullable=True),
    sa.Column('importo_totale', sa.Float(), nullable=True),
    sa.Column('nome_file', sa.String(), nullable=True),
    sa.Column('regime', sa.String(), nullable=True),
    sa.Column('stato', sa.String(), nullable=False),
    sa.Column('reminder_inviato', sa.Integer(), nullable=False),
    sa.Column('tipo_documento', sa.String(), nullable=True),
    sa.Column('fattura_rif_numero', sa.Integer(), nullable=True),
    sa.Column('fattura_rif_anno', sa.Integer(), nullable=True),
    sa.Column('data_creazione', app.models.FlexDateTime(), nullable=False),
    sa.Column('stripe_payment_link_id', sa.String(), nullable=True),
    sa.Column('stripe_payment_link_url', sa.String(), nullable=True),
    sa.Column('data_aggiornamento', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['lavoro_id'], ['lavori.id'], ),
    sa.ForeignKeyConstraint(['utente_id'], ['utenti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fatture_emesse', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fatture_emesse_id'), ['id'], unique=False)
        batch_op.create_index('ix_fatture_emesse_utente_anno', ['utente_id', 'anno'], unique=False)
        batch_op.create_index('ix_fatture_emesse_utente_id', ['utente_id'], unique=False)

    op.create_table('foto_lavori',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utente_id', sa.Integer(), nullable=False),
    sa.Column('lavoro_id', sa.Integer(), nullable=False),
    sa.Column('nome_file', sa.String(), nullable=False),
    sa.Column('percorso_file', sa.String(), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('data_creazione', app.models.FlexDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lavoro_id'], ['lavori.id'], ),
    sa.ForeignKeyConstraint(['utente_id'], ['utenti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('foto_lavori', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_foto_lavori_id'), ['id'], unique=False)

    op.create_table('garanzie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utente_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('lavoro_id', sa.Integer(), nullable=True),
    sa.Column('descrizione', sa.String(), nullable=False),
    sa.Column('data_installazione', app.models.FlexDate(), nullable=False),
    sa.Column('durata_mesi', sa.Integer(), nullable=False),
    sa.Column('data_scadenza', app.models.FlexDate(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('reminder_30g_inviato', sa.Integer(), nullable=True),
    sa.Column('reminder_7g_inviato', sa.Integer(), nullable=True),
    sa.Column('data_creazione', app.models.FlexDateTime(), nullable=False),
    sa.Column('data_aggiornamento', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clienti.id'], ),
    sa.ForeignKeyConstraint(['lavoro_id'], ['lavori.id'], ),
    sa.ForeignKeyConstraint(['utente_id'], ['utenti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('garanzie', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_garanzie_id'), ['id'], unique=False)
        batch_op.create_index('ix_garanzie_utente_id', ['utente_id'], unique=False)

    op.create_table('movimenti_magazzino',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utente_id', sa.Integer(), nullable=False),
    sa.Column('materiale_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('quantita', sa.Float(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('data_movimento', app.models.FlexDate(), nullable=False),
    sa.ForeignKeyConstraint(['materiale_id'], ['materiali.id'], ),
    sa.ForeignKeyConstraint(['utente_id'], ['utenti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movimenti_magazzino', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movimenti_magazzino_id'), ['id'], unique=False)

    op.create_table('pagamenti_lavoro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_ricevuta', sa.Integer(), nullable=True),
    sa.Column('utente_id', sa.Integer(), nullable=False),
    sa.Column('lavoro_id', sa.Integer(), nullable=False),
    sa.Column('data_pagamento', app.models.FlexDate(), nullable=False),
    sa.Column('importo', sa.Float(), nullable=True),
    sa.Column('metodo', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('data_creazione', app.models.FlexDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lavoro_id'], ['lavori.id'], ),
    sa.ForeignKeyConstraint(['utente_id'], ['utenti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pagamenti_lavoro', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pagamenti_lavoro_id'), ['id'], unique=False)

    op.create_table('prima_nota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utente_id', sa.Integer(), nullable=False),
    sa.Column('data', app.models.FlexDate(), nullable=False),
    sa.Column('descrizione', sa.String(), nullable=False),
    sa.Column('importo', sa.Float(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('fornitore_id', sa.Integer(), nullable=True),
    sa.Column('lavoro_id', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('aliquota_iva', sa.Float(), nullable=True),
    sa.Column('importo_iva', sa.Float(), nullable=True),
    sa.Column('data_creazione', app.models.FlexDateTime(), nullable=False),
    sa.Column('data_aggiornamento', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clienti.id'], ),
    sa.ForeignKeyConstraint(['fornitore_id'], ['fornitori.id'], ),
    sa.ForeignKeyConstraint(['lavoro_id'], ['lavori.id'], ),
    sa.ForeignKeyConstraint(['utente_id'], ['utenti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prima_nota', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prima_nota_id'), ['id'], unique=False)
        batch_op.create_index('ix_prima_nota_utente_id', ['utente_id'], unique=False)

    op.create_table('rapportini_lavoro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lavoro_id', sa.Integer(), nullable=False),
    sa.Column('utente_id', sa.Integer(), nullable=False),
    sa.Column('data', app.models.FlexDate(), nullable=False),
    sa.Column('ore_lavorate', sa.Float(), nullable=True),
    sa.Column('descrizione_attivita', sa.Text(), nullable=False),
    sa.Column('materiali_note', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('data_creazione', app.models.FlexDateTime(), nullable=False),
    sa.Column('data_aggiornamento', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['lavoro_id'], ['lavori.id'], ),
    sa.ForeignKeyConstraint(['utente_id'], ['utenti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rapportini_lavoro', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rapportini_lavoro_id'), ['id'], unique=False)

    op.create_table('sal_lavoro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lavoro_id', sa.Integer(), nullable=False),
    sa.Column('utente_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('data', app.models.FlexDate(), nullable=False),
    sa.Column('percentuale', sa.Float(), nullable=False),
    sa.Column('importo_richiesto', sa.Float(), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('stato', sa.String(), nullable=False),
    sa.Column('data_creazione', app.models.FlexDateTime(), nullable=False),
    sa.Column('data_aggiornamento', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['lavoro_id'], ['lavori.id'], ),
    sa.ForeignKeyConstraint(['utente_id'], ['utenti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sal_lavoro', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sal_lavoro_id'), ['id'], unique=False)

    op.create_table('sessioni_lavoro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lavoro_id', sa.Integer(), nullable=False),
    sa.Column('utente_id', sa.Integer(), nullable=False),
    sa.Column('inizio', app.models.FlexDateTime(), nullable=False),
    sa.Column('fine', app.models.FlexDateTime(), nullable=True),
    sa.Column('ore_calcolate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['lavoro_id'], ['lavori.id'], ),
    sa.ForeignKeyConstraint(['utente_id'], ['utenti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessioni_lavoro', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessioni_lavoro_id'), ['id'], unique=False)

    op.create_table('timesheet_collab',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lavoro_id', sa.Integer(), nullable=False),
    sa.Column('utente_id', sa.Integer(), nullable=False),
    sa.Column('nome_operaio', sa.String(), nullable=False),
    sa.Column('collaboratore_id', sa.Integer(), nullable=True),
    sa.Column('data', app.models.FlexDate(), nullable=False),
    sa.Column('ore', sa.Float(), nullable=False),
    sa.Column('costo_orario', sa.Float(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('data_creazione', app.models.FlexDateTime(), nullable=False),
    sa.Column('data_aggiornamento', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['collaboratore_id'], ['utenti.id'], ),
    sa.ForeignKeyConstraint(['lavoro_id'], ['lavori.id'], ),
    sa.ForeignKeyConstraint(['utente_id'], ['utenti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('timesheet_collab', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_timesheet_collab_id'), ['id'], unique=False)

    op.create_table('voci_preventivo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lavoro_id', sa.Integer(), nullable=False),
    sa.Column('utente_id', sa.Integer(), nullable=False),
    sa.Column('descrizione', sa.String(), nullable=False),
    sa.Column('quantita', sa.Float(), nullable=True),
    sa.Column('unita_misura', sa.String(), nullable=True),
    sa.Column('prezzo_unitario', sa.Float(), nullable=True),
    sa.Column('ordine', sa.Integer(), nullable=True),
    sa.Column('data_aggiornamento', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['lavoro_id'], ['lavori.id'], ),
    sa.ForeignKeyConstraint(['utente_id'], ['utenti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('voci_preventivo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voci_preventivo_id'), ['id'], unique=False)
        batch_op.create_index('ix_voci_preventivo_lavoro_id', ['lavoro_id'], unique=False)
        batch_op.create_index('ix_voci_preventivo_utente_id', ['utente_id'], unique=False)

    op.create_table('materiali_usati_lavoro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utente_id', sa.Integer(), nullable=False),
    sa.Column('lavoro_id', sa.Integer(), nullable=False),
    sa.Column('materiale_id', sa.Integer(), nullable=False),
    sa.Column('carico_id', sa.Integer(), nullable=True),
    sa.Column('quantita', sa.Float(), nullable=False),
    sa.Column('costo_unitario', sa.Float(), nullable=True),
    sa.Column('prezzo_unitario_cliente', sa.Float(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('data_creazione', app.models.FlexDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['carico_id'], ['carichi_materiale.id'], ),
    sa.ForeignKeyConstraint(['lavoro_id'], ['lavori.id'], ),
    sa.ForeignKeyConstraint(['materiale_id'], ['materiali.id'], ),
    sa.ForeignKeyConstraint(['utente_id'], ['utenti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('materiali_usati_lavoro', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_materiali_usati_lavoro_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materiali_usati_lavoro', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_materiali_usati_lavoro_id'))

    op.drop_table('materiali_usati_lavoro')
    with op.batch_alter_table('voci_preventivo', schema=None) as batch_op:
        batch_op.drop_index('ix_voci_preventivo_utente_id')
        batch_op.drop_index('ix_voci_preventivo_lavoro_id')
        batch_op.drop_index(batch_op.f('ix_voci_preventivo_id'))

    op.drop_table('voci_preventivo')
    with op.batch_alter_table('timesheet_collab', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_timesheet_collab_id'))

    op.drop_table('timesheet_collab')
    with op.batch_alter_table('sessioni_lavoro', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessioni_lavoro_id'))

    op.drop_table('sessioni_lavoro')
    with op.batch_alter_table('sal_lavoro', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sal_lavoro_id'))

    op.drop_table('sal_lavoro')
    with op.batch_alter_table('rapportini_lavoro', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rapportini_lavoro_id'))

    op.drop_table('rapportini_lavoro')
    with op.batch_alter_table('prima_nota', schema=None) as batch_op:
        batch_op.drop_index('ix_prima_nota_utente_id')
        batch_op.drop_index(batch_op.f('ix_prima_nota_id'))

    op.drop_table('prima_nota')
    with op.batch_alter_table('pagamenti_lavoro', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pagamenti_lavoro_id'))

    op.drop_table('pagamenti_lavoro')
    with op.batch_alter_table('movimenti_magazzino', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movimenti_magazzino_id'))

    op.drop_table('movimenti_magazzino')
    with op.batch_alter_table('garanzie', schema=None) as batch_op:
        batch_op.drop_index('ix_garanzie_utente_id')
        batch_op.drop_index(batch_op.f('ix_garanzie_id'))

    op.drop_table('garanzie')
    with op.batch_alter_table('foto_lavori', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_foto_lavori_id'))

    op.drop_table('foto_lavori')
    with op.batch_alter_table('fatture_emesse', schema=None) as batch_op:
        batch_op.drop_index('ix_fatture_emesse_utente_id')
        batch_op.drop_index('ix_fatture_emesse_utente_anno')
        batch_op.drop_index(batch_op.f('ix_fatture_emesse_id'))

    op.drop_table('fatture_emesse')
    with op.batch_alter_table('fatture_acquisto', schema=None) as batch_op:
        batch_op.drop_index('ix_fatture_acquisto_utente_id')
        batch_op.drop_index('ix_fatture_acquisto_utente_anno')
        batch_op.drop_index(batch_op.f('ix_fatture_acquisto_id'))

    op.drop_table('fatture_acquisto')
    with op.batch_alter_table('documenti_pdf', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documenti_pdf_id'))

    op.drop_table('documenti_pdf')
    with op.batch_alter_table('carichi_materiale', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_carichi_materiale_id'))

    op.drop_table('carichi_materiale')
    with op.batch_alter_table('allegati_lavoro', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_allegati_lavoro_id'))

    op.drop_table('allegati_lavoro')
    with op.batch_alter_table('promemoria_clienti', schema=None) as batch_op:
        batch_op.drop_index('ix_promemoria_utente_id')
        batch_op.drop_index(batch_op.f('ix_promemoria_clienti_id'))

    op.drop_table('promemoria_clienti')
    with op.batch_alter_table('materiali', schema=None) as batch_op:
        batch_op.drop_index('ix_materiali_utente_id')
        batch_op.drop_index(batch_op.f('ix_materiali_id'))

    op.drop_table('materiali')
    with op.batch_alter_table('lavori', schema=None) as batch_op:
        batch_op.drop_index('ix_lavori_utente_stato_fattura')
        batch_op.drop_index('ix_lavori_utente_stato')
        batch_op.drop_index('ix_lavori_utente_id')
        batch_op.drop_index(batch_op.f('ix_lavori_id'))
        batch_op.drop_index('ix_lavori_cliente_id')

    op.drop_table('lavori')
    with op.batch_alter_table('template_preventivi', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_template_preventivi_id'))

    op.drop_table('template_preventivi')
    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_subscriptions_id'))

    op.drop_table('push_subscriptions')
    with op.batch_alter_table('listino_voci', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listino_voci_id'))

    op.drop_table('listino_voci')
    with op.batch_alter_table('inviti_account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inviti_account_id'))

    op.drop_table('inviti_account')
    with op.batch_alter_table('impostazioni_azienda', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_impostazioni_azienda_id'))

    op.drop_table('impostazioni_azienda')
    with op.batch_alter_table('fornitori', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fornitori_id'))

    op.drop_table('fornitori')
    with op.batch_alter_table('clienti', schema=None) as batch_op:
        batch_op.drop_index('ix_clienti_utente_id')
        batch_op.drop_index(batch_op.f('ix_clienti_id'))

    op.drop_table('clienti')
    with op.batch_alter_table('utenti', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_utenti_id'))

    op.drop_table('utenti')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_log_utente_ts')

    op.drop_table('audit_log')
    # ### end Alembic commands ###
