name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11.9"
          cache: "pip"

      - name: Installa le dipendenze
        run: pip install -r requirements.txt

      - name: Esegui la suite di test
        run: python -m pytest
